[theme]
primaryColor = "#16a34a"
backgroundColor = "#f8f9fa"
secondaryBackgroundColor = "#ffffff"
textColor = "#1a202c"
font = "sans serif"

[server]
runOnSave = false

[client]
showErrorDetails = false

[browser]
gatherUsageStats = false
